### PR TITLE
This is the Silk.NET Mobile Update (v2.22.0)

### PR DESCRIPTION
**Pull request by Beyley**
# Summary of the PR
the j

### CODE REVIEW

**Comment by Perksey** [comment]
What's the progress on this?

**Comment by Beyley** [comment]
> What's the progress on this?

two native lib builds are broken and i havent found the time/energy to fix them yet, as ive had people over the past 2 or so weeks

https://github.com/dotnet/Silk.NET/actions/runs/9187481791/job/25265261947?pr=2184
https://github.com/dotnet/Silk.NET/actions/runs/9187481793/job/25265262150?pr=2184

**Comment by Perksey** [comment]
Ok, will try to find the time soon.

**Comment by tonisimakov99** [comment]
@Perksey, A small request for #2298, Handle needs to be in HEX format, because Vulkan returns pointers in HEX. For example, "Invalid VkDescriptorSet Object 0x74ea280000000054"

**Comment by Perksey** [comment]
Costs extra ;) no problem, will do

**Comment by Perksey** [comment]
This is done now I think. Will double check mobile is still working in the morning. Self-review over the entire PR was complete, mostly focusing on file edits as I think the generator is as trusted now as it'll ever be for new files. Changed one thing where DWrite for some reason was generating a D2D1 type, and also updated some of the submodules again as they hadn't been updated since May (yes this PR has been open that long).

WebGPU triangle and ImGui Vulkan (as per #2240) have been tested, and I'll be testing OpenGL with the mobile stuff tomorrow. @Beyley @HurricanKai feel free to try and break this even further if you feel like it but I couldn't identify any potentially nasty changes.

**Review by Perksey — APPROVED** [review]
\~yes\~ THIS IS READY \~yes\~

image

(WebGPU Triangle tested on Windows, OpenGLES Triangle tested on iOS and Android, OpenGL tutorial 3.5 tested on Windows and macOS)

**Comment by Beyley** [comment]
since its my PR im physically incapable of approving it, however

image

**Pull request merged**
