### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by Perksey**
I don't know how this works so I'm just going off what other dotnet repos do. Should be good to merge but I don't know if it's enough...

### CODE REVIEW

**Comment by HurricanKai** [comment]
I was relatively certain this was automatically detected anyways. I'll review and get back to you

**Comment by HurricanKai** [comment]
I was relatively certain this was automatically detected anyways. I'll review and get back to you

**Comment by Perksey** [comment]
Eh can't be bothered with this

**Comment by Perksey** [comment]
Reopening this as I'd quite like to get it in. @HurricanKai did you find out anything about this?

It looks like Dependabot doesn't pick up on a repo (unless there's a security vulnerability in a package) by default, so we have to enable it using a YAML file but if you've found otherwise let me know.

**Review by HurricanKai — APPROVED** [review]
Sure

**Pull request merged**
