### PR TITLE
This is the October 2023 Update (v2.18.0)

### PR DESCRIPTION
**Pull request by Perksey**
The `Use` functions rely on reflection doing the right things, which isn't necessarily correct on AOT.

### CODE REVIEW

**Comment by Perksey** [comment]
Need to do input as well

**Comment by Perksey** [comment]
Need to write the patch notes tomorrow and regen bindings. This shall be the last manual update, I decree it!

**Comment by Perksey** [comment]
This is ready for review & release

**Review by Beyley — APPROVED** [review]
yas bros... i'ts lookoing good

**Pull request merged**
