### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Perksey**
no idea

### CODE REVIEW

**Comment by Perksey** [comment]
*Also upgraded NUKE FWIW, so any changes to the script/csproj/nuke files are done by NUKE and not me.

**Comment by Perksey** [comment]
Pretty urgently needs review, all 2.X PRs are currently failing build and we haven't had any experimental builds for a while.

**Comment by HurricanKai** [comment]
Seems like the check is still failing? Am available for review all day

**Comment by Perksey** [comment]
CI Build is passing, Public API is known-failing and I can't be bothered to fix it right now.

**Review by HurricanKai — APPROVED** [review]
LGTM

**Pull request merged**
