### PR TITLE
Minor proposal changes

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
# Summary of the PR
Updates to proposals

### CODE REVIEW

**Comment by Perksey** [comment]
Needs working group sign-off, added to list for next meeting.

**Comment by WhiteBlackGoose** [comment]
🙄 when is it going to be? `Not` is not going to work without `AllBitsSet` property

**Comment by Perksey** [comment]
There's no date at the moment, and there's still feedback from the last working group meeting we need to address. Will try to work on that this evening/this weekend to further it along.

**Comment by WhiteBlackGoose** [comment]
._. sounds beurocratic to me.

Now that means that my whole PR which implements `AllBitsSets` will be frozen for a while. Maybe I can remove `Not` and `AllBitsSet` from it though...

**Review by Perksey — APPROVED** [review]
Actually on second glance this seems fine and is a continuation of the already-approved message of "like Scalar but with Vectors". The main thing I was concerned about in the details of the bitshifts, but it looks like there were addressed in the last meeting. Approving

**Pull request merged**
