### PR TITLE
[Draft] Create iOS build scripts for shaderc, SPIRV-Cross, etc.

### PR DESCRIPTION
**Pull request by yodasoda1219**
# Summary of the PR
Build iOS binaries for SPIR-V APIs alongside desktop targets for MoltenVK/mobile shader cross-compilation support.

# Related issues, Discord discussions, or proposals
See [messages sent in the Discord server](https://discord.com/channels/521092042781229087/607634593201520651/1165442640293154876).

# Further Comments
N/A

### CODE REVIEW

**Comment by yodasoda1219** [comment]
@dotnet-policy-service agree

**Comment by Perksey** [comment]
Hey, thanks so much for looking into contributing! Is this still in progress?

**Comment by yodasoda1219** [comment]
Hey! My apologies, I got sidetracked with other projects. I do want to continue this at some point, however currently it is not in progress.

**Comment by Perksey** [comment]
No worries! I'll shut this off for now but please feel free to reopen if you find the time again! We always love community contributions and appreciate you even taking the time to investigate contributing!

**Pull request closed without merging**
