### PR TITLE
GLFW3.dll missing in Net461 projects

### PR DESCRIPTION
**Pull request by paralaxsd**
This fixes an issue for a consuming .net4 applications as demonstrated at https://github.com/paralaxsd/ultz.native.glw-framework-test and discussed in https://github.com/dotnet/Silk.NET/issues/1356

# Summary of the PR
When using .net 4.6.1, referencing the `Ultz.Native.GLFW` package will not copy the `glfw3.dll` library to the output directory.

### CODE REVIEW

**Comment by paralaxsd** [comment]
Two things:
* currently, the nuget package version is set to `3.3.10-alpha`. Should I bump this up to `3.3.10`?
* It's probably sensible to also adapt the `Silk.NET.SDL.Native` project since it works exactly the same. What do you think?

**Comment by HurricanKai** [comment]
I believe adapting SDL also makes sense, but we only really use SDL on mobile, which I can't imagine works on net461 anyways. I'd be happy to merge this regardless, but if you make the same changes for SDL that'd be good.

Versioning I'd defer to @Beyley or @Perksey, not sure if there's any real versioning strategy for the native packages :stuck_out_tongue:

**Comment by Perksey** [comment]
We use this pattern in all the native libs, makes sense to change it everywhere at once.

We tend to use the 4th version number as the silk-specific version number. So just whack a .1 at the end of the versions if there isn't already a 4th number

**Comment by paralaxsd** [comment]
Ok since this was originally `3.3.9`, I'd go with `3.3.9.1` then.

**Comment by paralaxsd** [comment]
Made changes to all native projects. There were however three projects that took their package version from `..\..\..\build\props\common.props`. I didn't change those for the time being as I'm not sure if I should: `Silk.NET.OpenGLES.ANGLE.Native`, `Silk.NET.Vulkan.Loader.Native`, `Silk.NET.Vulkan.SwiftShader.Native`

**Comment by Perksey** [comment]
No worries :) those version numbers are tied to the git submodule SHAs so they'll get swept up next time we update those submodules and regenerate their bindings.

**Review by Perksey — APPROVED** [review]

**Pull request merged**
