### PR TITLE
.NET Foundation Onboarding

### PR DESCRIPTION
**Pull request by Perksey**
# Project Onboarding

- Public Announcement via the .NET Foundation site/etc - **External**
- Joining the Project leader mailing list - **External**
- Joining the Project leader Slack channel - **External**
- [x] Updating license/copyright in the repo + updating file headers
- [x] Reviewing the .NET Foundation Code of Conduct
- Add Project to the .NET Foundation project list - **External**
- [x] Project layout cleanup (as appropriate)
- [x] README Guidance updates
- Project website updates (outside of GitHub) - **No external websites but one will be made post-onboarding**
- Enable two-factor authentication (2FA) for GitHub - **We're all already 2FA**

Related dotnet-foundation/projects#115

### CODE REVIEW

**Comment by Perksey** [comment]
cc @ChrisSfanos:
- We've updated the CoC (we were already using the Contributor Covenant so we had no issues in adopting the .NET Foundation CoC)
- We've updated all copyright and license headers
- I don't think any project layout adjustments are required, but if you think there are that'd be great.
- We've updated the README file which can be viewed [here](https://github.com/Ultz/Silk.NET/blob/feature/dotnetfoundation/README.md), if you think any further changes are required let me know.

**Comment by ChrisSfanos** [comment]
Readme looks good
Once you push the changes, I'll validate everything. (my quick scan of the commits above look good for CoC, etc

**Comment by Perksey** [comment]
Awesome, thanks Chris. @HurricanKai this is ready for review and merge.

**Review by HurricanKai — APPROVED** [review]
Looks good. Obviously not looked at anything but the couple of files that should've changed.

**Pull request merged**
