### PR TITLE
Unconstraining Scalar ; adding BigInteger and Complex

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
# Summary of the PR
Unconstraining `T` in `Scalar<>` and adding `BigInteger` and `Complex`

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Hold on, I forgot to change the docs

**Comment by WhiteBlackGoose** [comment]
It's just not displayed by GH's Files Changed tab

**Comment by HurricanKai** [comment]
Oh, why is that, where can I view those changes then?

**Comment by WhiteBlackGoose** [comment]
@HurricanKai  easy to miss :)
D8E94D11-5E90-43B6-A8D9-7182004BF0D5

**Comment by HurricanKai** [comment]
Fantastic, thank you.
UI in the app is even better:

**Pull request merged**
