### PR TITLE
First class DXVK support

### PR DESCRIPTION
**Pull request by Beyley**
# Summary of the PR
- [x] Windows native libraries
- [x] Linux SDL native libraries
- [x] Linux GLFW native libaries
- [x] Add overload on functions like D3D11.GetApi() to force DXVK and to let the user pass in an `IWindow` so we pick the right native libraries on Linux (there are entirely different versions of the binary for SDL and GLFW)
- [x] Test D3D11 [example](https://github.com/dotnet/Silk.NET/tree/main/examples/CSharp/Direct3D11%20Tutorials/Tutorial%201.2%20-%20Hello%20quad) on DXVK on windows
- [x] Get D3D11 [example](https://github.com/dotnet/Silk.NET/tree/main/examples/CSharp/Direct3D11%20Tutorials/Tutorial%201.2%20-%20Hello%20quad) working under Linux natively using DXVK
- [x] D3DCompile replacement

# Further Comments
I need to contact the DXVK developers about best practices with packaging DXVK (both Windows and Linux versions), so we dont pull a Manjaro

### CODE REVIEW

**Comment by Beyley** [comment]
Current blocker: we need to provide a modified version of vkd3d, and getting that to load seems to require LD_LIBRARY_PATH modifications, due to cross-library dependencies
```patch
diff --git a/include/vkd3d_windows.h b/include/vkd3d_windows.h
index 002ff667..097a4787 100644
--- a/include/vkd3d_windows.h
+++ b/include/vkd3d_windows.h
@@ -186,7 +186,7 @@ typedef struct SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;
         ((type *)((char *)(address) - offsetof(type, field)))
 
 # ifdef __x86_64__
-#  define __stdcall __attribute__((ms_abi))
+#  define __stdcall 
 # else
 #  if (__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 2)) || defined(__APPLE__)
 #   define __stdcall __attribute__((__stdcall__)) __attribute__((__force_align_arg_pointer__))
```

**Comment by Beyley** [comment]
> Current blocker: we need to provide a modified version of vkd3d, and getting that to load seems to require LD_LIBRARY_PATH modifications, due to cross-library dependencies
> 
> ```diff
> diff --git a/include/vkd3d_windows.h b/include/vkd3d_windows.h
> index 002ff667..097a4787 100644
> --- a/include/vkd3d_windows.h
> +++ b/include/vkd3d_windows.h
> @@ -186,7 +186,7 @@ typedef struct SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;
>          ((type *)((char *)(address) - offsetof(type, field)))
>  
>  # ifdef __x86_64__
> -#  define __stdcall __attribute__((ms_abi))
> +#  define __stdcall 
>  # else
>  #  if (__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 2)) || defined(__APPLE__)
>  #   define __stdcall __attribute__((__stdcall__)) __attribute__((__force_align_arg_pointer__))
> ```

Thinking about it, if we load the dependencies of vkd3d-utils using dlopen before doing dlopen on vkd3d-utils, it should work, so perhaps a `params string[]` parameter on CreateDefaultContext to specify pre-load dependencies would work? itd be something like `CreateDefaultContext("vkd3d-utils", "vkd3d", "vkd3d-shader")` to specify to load vkd3d, then vkd3d-shader as dependencies, then load vkd3d-utils

**Comment by Perksey** [comment]
Plumbing it into CreateDefaultContext probably isn't the best. Maybe something like:
```cs
partial class D3DCompiler
{
    static D3DCompiler()
    {
        // static method
        LibraryLoader.RegisterDependency("vkd3d-utils", "vkd3d", "vkd3d-shader");
    }
}
```

and plumb it into `LibraryLoader` directly. SilkTouch probably shouldn't know about intercepting the load calls to do extra work beforehand, and should probably just be a loader specific task.

**Comment by Beyley** [comment]
> Plumbing it into CreateDefaultContext probably isn't the best. Maybe something like:
> 
> ```cs
> partial class D3DCompiler
> {
>     static D3DCompiler()
>     {
>         // static method
>         LibraryLoader.RegisterDependency("vkd3d-utils", "vkd3d", "vkd3d-shader");
>     }
> }
> ```
> 
> and plumb it into `LibraryLoader` directly. SilkTouch probably shouldn't know about intercepting the load calls to do extra work beforehand, and should probably just be a loader specific task.

makes sense

**Comment by Beyley** [comment]
oh my god i just saw the CI what

**Comment by Beyley** [comment]
ready for review, but not ready for merge until i can get in contact with the dxvk/vkd3d people, i dont want to push broken libs

**Comment by Perksey** [comment]
Status update?

**Comment by Beyley** [comment]
> Status update?

DXVK on windows needs testing, but aside from that, it's ready for review

**Comment by Perksey** [comment]
Did you want it merged without that though?

**Comment by Beyley** [comment]
> Did you want it merged without that though?
it's fine to wait until someone can test, this PR shouldnt block releases, and i dont want to be merging in like 15mb of native libs that dont even work

**Comment by Perksey** [comment]
This needs a rebase.

If you can give me binaries and exact instructions I can test on Windows.

**Comment by Beyley** [comment]
> This needs a rebase.
> 
> If you can give me binaries and exact instructions I can test on Windows.

@Perksey 

All you need to do is go into the `src/Native/Silk.NET.Vkd3d.Native`, run a `dotnet pack`, do the same with the DXVK native package, then you want to add the nuget source, then apply this patch:
```patch
diff --git a/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Program.cs b/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Program.cs
index 3ba233a72..4451f27a7 100644
--- a/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Program.cs	
+++ b/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Program.cs	
@@ -113,7 +113,7 @@ window.Dispose();
 unsafe void OnLoad()
 {
     //Whether or not to force use of DXVK on platforms where native DirectX implementations are available
-    const bool forceDxvk = false;
+    const bool forceDxvk = true;
 
     dxgi = DXGI.GetApi(window, forceDxvk);
     d3d11 = D3D11.GetApi(window, forceDxvk);
diff --git a/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Tutorial 1.2 - Hello quad.csproj b/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Tutorial 1.2 - Hello quad.csproj
index eddc35792..dfc1d4d7d 100644
--- a/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Tutorial 1.2 - Hello quad.csproj	
+++ b/examples/CSharp/Direct3D11 Tutorials/Tutorial 1.2 - Hello quad/Tutorial 1.2 - Hello quad.csproj	
@@ -16,6 +16,9 @@
       <ProjectReference Include="..\..\..\..\src\Microsoft\Silk.NET.Direct3D11\Silk.NET.Direct3D11.csproj" />
       <ProjectReference Include="..\..\..\..\src\Microsoft\Silk.NET.DXGI\Silk.NET.DXGI.csproj" />
       <ProjectReference Include="..\..\..\..\src\Windowing\Silk.NET.Windowing\Silk.NET.Windowing.csproj" />
+
+      <PackageReference Include="Silk.NET.Vkd3d.Native" Version="2.17.0" />
+      <PackageReference Include="Silk.NET.DXVK.Native" Version="2.17.0" />
     </ItemGroup>
 
 </Project>

```

then when running the d3d11 tutorial, it should use DXVK (you can look at console output, there should be a bunch of stuff printed from DXVK)

**Review by Perksey — APPROVED** [review]

**Pull request merged**
