### PR TITLE
Start of rotate vector by quaternion with multiplication operator

### PR DESCRIPTION
**Pull request by qhdwight**
# Summary of the PR
Adds the ability to "multiply" a vector by a quaternion, effectively rotating it. This is supported by Unity.

Mock implementation (no operator signature yet):
```csharp
public static Vector3D<double> Rotate(in Vector3D<double> v, in Quaternion<double> q)
{
    Debug.Assert(Math.Abs(q.LengthSquared() - 1.0) < 1e-6f);
    var u = new Vector3D<double>(q.X, q.Y, q.Z);
    double s = q.W;
    return 2.0 * Vector3D.Dot(u, v) * u
         + (s * s - Vector3D.Dot(u, u)) * v
         + 2.0 * s * Vector3D.Cross(u, v);
}
```

# Related issues, Discord discussions, or proposals
https://gamedev.stackexchange.com/questions/28395/rotating-vector3-by-a-quaternion

# Further Comments
I was looking for a builtin function, couldn't seem to find it (or wasn't obvious)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=810) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=810) before we can accept your contribution.<br/><br/>:x: qhdwight [sign now](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=810)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Silk.NET?pullRequest=810) it.</sub>

**Comment by Perksey** [comment]
We'll be happy to accept this if you're still willing to contribute it! I notice there hasn't been any commits yet.

**Comment by qhdwight** [comment]
Oops been a bit busy, will try to make some commits this weekend

**Comment by qhdwight** [comment]
What else should I add, public interface, unit testing?

**Comment by HurricanKai** [comment]
Adding unit testing to the test project would be much appreciated

**Comment by Perksey** [comment]
Has there been any update on this? @HurricanKai this has been open for a while, how much do you care about the unit testing?

**Comment by Perksey** [comment]
bump @HurricanKai do we merge without testing or close for inactivity?

**Comment by HurricanKai** [comment]
I don't have the time to verify or add the remaining function signatures. Closing for inactivity. Feel free to reopen or start a new PR.

**Pull request closed without merging**
