### PR TITLE
Add IKeyboard function to check scancode pressed state

### PR DESCRIPTION
**Pull request by ThomasMiz**
# Summary of the PR
Add and implement an `IKeyboard` function to check whether a key by scancode is pressed or released.

# Related issues, Discord discussions, or proposals
#1235 

# Further Comments
I will also modify Lab/InputTest so I can verify correct behavior

### CODE REVIEW

**Comment by ThomasMiz** [comment]
> We could implement this like so:
> 
> * In the GLFW backend, we can easily use [glfwGetKeyScancode()](https://www.glfw.org/docs/latest/group__input.html#ga67ddd1b7dcbbaff03e4a76c0ea67103a)
> * SDL will be more complicated as it has no such function. `SdlKeyboard.IsKeyPressed(Key key)` is implemented as a `List<Key> _keysDown`, with the list updated every time the keydown/keyup event occurs. We could do the same for scancodes, or maybe more appropiately turn this list into a list of scancodes and update the `SdlKeyboard` code like so:
> 
> ```cs
> public bool IsKeyPressed(Key key) => _keysDown.Contains(key);
> public bool IsScancodePressed(int scancode) => _scancodesDown.Any(x => _keyMap.TryGetValue(x, out var skey) && key == skey);
> ```


Update:
I was wrong, `glfwGetKeyScancode` is not useful for this. We'll also need to implement a scancode list on GLFW.

💀

**Comment by Perksey** [comment]
What was the issue with it?

**Comment by ThomasMiz** [comment]
I thought `glfwGetKeyScancode` was like `glfwGetKey` but for scancodes, as in, to get the key's state. It turns out it's actually for converting a scancode to key

**Review by Perksey — APPROVED** [review]
We could bikeshed the name more but this seems benign - happy for this not to go to API review.

**Comment by Perksey** [comment]
Build is failing though

**Comment by ThomasMiz** [comment]
I built the solution and ran the InputTest no problem though

**Comment by ThomasMiz** [comment]
Ah, I used visual studio's suggestion to auto-add the method to the PublicAPI thing and it seems to have only modified PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt. I have no idea how these work

**Comment by Perksey** [comment]
You can use NUKE to do this for all of them if you'd like `nuke declareapi`

**Comment by ThomasMiz** [comment]
> You can use NUKE to do this for all of them if you'd like `nuke declareapi`

Done. It just added the same line to the other netstandard file, lol

**Comment by Perksey** [comment]
Build is still failing, can you ensure the public API additions are in every TFM

**Comment by ThomasMiz** [comment]
> Build is still failing, can you ensure the public API additions are in every TFM

Then the `nuke declareapi` didn't do it's job properly. It added `IsScancodePressed` to the PublicAPI.Unshipped.txt files for netstandard 2.0 and 2.1. If I understood how these work, it should have instead been added to the PublicAPI.Shipped.txt files for all TFMs.

I did so manually. Let's hope this works!

**Comment by ThomasMiz** [comment]
@Perksey Build is now succeeding. Anything else before we merge this?

**Review by Perksey — APPROVED** [review]

**Pull request merged**
