### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
🦆

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Or is it not a typo? But vector is fixed-size, not length, so it won't work

**Comment by HurricanKai** [comment]
It's intentional, you only want the sign in those, so aligning with BCL int makes sense.
Could consider having a copy sign method or changing it though

**Comment by WhiteBlackGoose** [comment]
[Discussion in discord](https://discord.com/channels/521092042781229087/587346162802229298/907982387802173450)

**Review by HurricanKai — APPROVED** [review]

**Review by HurricanKai — CHANGES_REQUESTED** [review]
This looks good to me, but I apparently can't make it wait for @Perksey s review.
Can we change this as is or do we need to take this back for review?

**Review by Perksey — APPROVED** [review]
Nothing functional or logical is changing, good for merge.

**Review by HurricanKai — APPROVED** [review]

**Pull request merged**
