### PR TITLE
[Experimental] CodegenAnalysis benchmarks

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
Report that they generate can be found [**here**](https://gist.github.com/WhiteBlackGoose/e452ea5351a73a698b21aedc44441593) (warning: *big* file).

(there's a markdown table (it's not well fitted, you might wanna scroll right), and then there's a list of codegens for each benched function (note that in benchmarks those are loops!))

@HurricanKai what do you think?

### CODE REVIEW

**Comment by Perksey** [comment]
Note: all dependencies added pass the license check.

**Comment by WhiteBlackGoose** [comment]
What's that? 😅 
The lib's under MIT

**Comment by Perksey** [comment]
Yes I know, that’s why I said it *passed* the license check. All other dependencies added are also MIT or MIT-compatible.

**Comment by Perksey** [comment]
Closing draft PR due to inactivity.

**Pull request closed without merging**
