### PR TITLE
Proposal - 3.0 Additional types for Silk.NET.Maths

### PR DESCRIPTION
**Pull request by dfkeenan**
# Summary of the PR
A proposal for additional types to the Silk.NET.Maths library for 3.0.

# Related issues, Discord discussions, or proposals
As discussed in discord with the SilkX team.

### CODE REVIEW

**Comment by dfkeenan** [comment]
@dotnet-policy-service agree

**Comment by Perksey** [comment]
Provisionally adding this to the next working group meeting agenda.

**Comment by uwx** [comment]
Angle (and other such types) shouldn't have a public constructor, that completely voids the point of having the type as it's not clear what underlying unit is being passed in without reading the code. That's why we have FromDegrees and FromRadians. `Angle.Sin(new Angle(1.0))` is no more clear than `Math.Sin(1.0)`, but `Angle.Sin(Angle.FromRadians(1.0))` is.

**Comment by Perksey** [comment]
Hey! How's the progress here? :)

**Comment by dfkeenan** [comment]
> Hey! How's the progress here? :)

Yo!

Sorry, this got put on the back burner due to other stuff. To be honest not sure what state it is in. 😅

I do remember wanting to discuss some things about the design with the team. Looking at the proposals the `Angle` and `Color` proposals look pretty close, There does appear to be some obvious blank spots in the `Collision` proposal. 

Might be worth getting some feed back from some other people. Not sure if you want to bring it to the next 3.0 meeting.

**Comment by dfkeenan** [comment]
The proposals I started aren't quite there yet but I don't want to keep working on them at the moment. I have marked them as work in progress so perhaps someone else can take over.

**Review by Perksey — APPROVED** [review]

**Pull request merged**
