### PR TITLE
Start of multi-partials

### LINKED ISSUE #384: Add support for multiple partials in SilkTouch

### PR DESCRIPTION
**Pull request by HurricanKai**
Closes #384

### CODE REVIEW

**Comment by HurricanKai** [comment]
@Perksey This appears to work in test cases - while I'm confident it should work in others too, can you check / tell me where we need this?

**Comment by HurricanKai** [comment]
Also note that this PR upgrades our required global.json version to 5.0.201, this is required for using Roslyn 3.9.0.

**Comment by Perksey** [comment]
There's a file called Sdl.SysWM.Cs with a #if false in there. Remove the #if false and see if it works :D

**Comment by HurricanKai** [comment]
Seems like it works. Just *slowly* but perf optimization isn't part of this PR :)

**Review by Perksey — APPROVED** [review]
LGTM, ideally we'd have some named structs or named tuples so it's obvious what all the Item1 means, but that can be done as part of #300

**Review by Perksey — CHANGES_REQUESTED** [review]
Changed my mind: fix the build errors please :D

**Comment by Perksey** [comment]
Can you retarget this to the latest main?

**Comment by HurricanKai** [comment]
Apologies for the force push - git has been acting up so I just rebased locally and force pushed.

**Review by Perksey — APPROVED** [review]

**Pull request merged**
