### PR TITLE
Add more OpenGL + Direct3D demos

### PR DESCRIPTION
**Pull request by skyebird189**
# Summary of the PR
This PR aims to add some more OpenGL and Direct3D demos, including:
* Simple rotating textured cube
* Very basic sprite renderer
* Instancing demo
* Basic 3D render engine with phong lighting and basic shadow mapping (+ potentially model loading)

# Related issues, Discord discussions, or proposals
https://discord.com/channels/521092042781229087/587346162802229298/1129506878309814342

# Further Comments
I will be rearranging the `examples` directory structure to the following:
```
examples/
└── CSharp/
    ├── Tutorials/
    │   ├── OpenGL/
    │   └── Direct3D11/
    └── Demos/
        ├── Common/
        ├── OpenGL/
        └── Direct3D11/
```

Please let me know if this is a problem - I just personally think this will make the `examples` directory easier to navigate (since I will be adding several new projects + their directories).

### CODE REVIEW

**Comment by Perksey** [comment]
We had a long discussion both in #474 and in Discord on what this structure should be, and I don't think we should really have those arguments again. Recommend sticking with what we have now, and that way we don't break everyone's hyperlinks :P

**Comment by skyebird189** [comment]
Alrighty, I will keep the structure the same

**Comment by Perksey** [comment]
Just wanted to check in on this?

**Comment by skyebird189** [comment]
Sorry, didn't see this. I'm gonna close this for now as I'm busy working on personal projects and I'm unlikely to work on this anytime soon.

**Pull request closed without merging**
