### PR TITLE
[3.0] Contributor experience improvements

### PR DESCRIPTION
**Pull request by Perksey**
- Adds a basic for-contributors getting started README for building the repo, detailing what you need to get started. Closes #2403 which also does the same.
- Adds a "best effort" attempt to resolve native binaries when used as a `ProjectReference`.
- Adds the ability to disable building for Android/iOS by adding properties to Directory.Build.props which are then used when setting `TargetFrameworks`

### CODE REVIEW

**Comment by Perksey** [comment]
The PR check is triggering because I've modified the native project to not include an Android build if disabled. This does not warrant a rebuild.

**Comment by Perksey** [comment]
@curin Ready for review.

**Review by curin — APPROVED** [review]

**Comment by Perksey** [comment]
@joskuijpers hopefully this helps? PTAL

**Comment by joskuijpers** [comment]
Good changes! Playground now runs without SDL DLL issues, and the contributor document was very useful too.

**Pull request merged**
