### PR TITLE
Add a Rider/ReSharper plugin

### PR DESCRIPTION
**Pull request by Perksey**
More words will be here in due course.

### CODE REVIEW

**Comment by Perksey** [comment]
I think the next steps for this is fixing up the overloads so that they're less specific/hardcoded, and then cleaning up the code a bit (i.e. removing commented out stuff). I'm happy to ship with the functionality we have now given those two points.

**Comment by Perksey** [comment]
The longest-standing PR currently open today is now ready for review.

**Comment by Perksey** [comment]
In case the reader is not aware: we have decided not to include codefixes at this time due to time constraints on the maintenance team. We definitely want this however and will accept community contributions for adding them.

**Comment by HurricanKai** [comment]
(Code fixes are expected for 3.0)

**Comment by Perksey** [comment]
Will try and revisit this for 2.16, sorry this is taking so long.

**Comment by Perksey** [comment]
I'm closing this as I won't be coming back to this, and with all maintainers being dedicated to 3.0 I'm not sure if anyone else would either. I've protected the branch, so it should stay put should anyone else want to pick this up.

**Pull request closed without merging**
