### PR TITLE
Fix wide string marshalling

### PR DESCRIPTION
**Pull request by Perksey**

### CODE REVIEW

**Review by Beyley — APPROVED** [review]
bro WHAT A⹳坒祂整摁牤獥䉳晵敦獲㜮

**Comment by HurricanKai** [comment]
Random that I saw this, but this doesn't seem like it'd work?
Won't this just write a 0 in the middle of the array?
Iirc it should null terminate (which is why the +1 existed) so it should be allocating input.Length * 2 + 1 and write to input.Length * 2?

**Comment by Beyley** [comment]
> Random that I saw this, but this doesn't seem like it'd work? Won't this just write a 0 in the middle of the array? Iirc it should null terminate (which is why the +1 existed) so it should be allocating input.Length * 2 + 1 and write to input.Length * 2?

theres a second line of code writing the null terminator
image

**Comment by Beyley** [comment]
oh shit

**Comment by Perksey** [comment]
@Beyley Can you please be careful with language on GitHub? Appreciate the team is quite colloquial on Discord, but GitHub tends to be more formal :)

**Pull request merged**
