### PR TITLE
OpenAL MCFormats extension

### PR DESCRIPTION
**Pull request by aleksrutins**
# Summary of the PR
This PR adds support for the `AL_EXT_MCFORMATS` extension.

# Related issues, Discord discussions, or proposals
Help was asked for here: <https://discordapp.com/channels/521092042781229087/727266595826696303/1142111300336500766>. It seemed like finally something I could do and understand, so here we are. 

# Further Comments
_none_

### CODE REVIEW

**Comment by aleksrutins** [comment]
@dotnet-policy-service agree

**Comment by aleksrutins** [comment]
Oddly, I couldn't find any docs whatsoever about AL_FORMAT_REAR{8,16,32} - if someone could point me to some, so I can put them here, it would be greatly appreciated.

**Comment by Perksey** [comment]
This is the best I have unfortunately https://github.com/Raulshc/OpenAL-EXT-Repository/blob/master/AL%20Extensions/AL_EXT_MCFORMATS.txt

**Review by Perksey — APPROVED** [review]
Beautiful, thank you! Ping me in Discord if you want a purple name

**Pull request merged**
