### PR TITLE
Codegen tests (experimental)

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
Working on tests verifying the correct JIT codegen

### CODE REVIEW

**Comment by HurricanKai** [comment]
Just a heads up, I might end up throwing the majority of this out with the new test suite.

**Comment by WhiteBlackGoose** [comment]
Could you elaborate?

**Comment by WhiteBlackGoose** [comment]
For now I keep integer types out of the tests, because they give bad codegen in a lot of cases, as well as all 64-bit ops. (out of all 750 tests, 239 failed).

I'm opening this as ready for review, but there's no need to rush with review, it's not blocking me.

Also if you don't like failing tests, I'll think what we can do about them

**Comment by HurricanKai** [comment]
We should probably port something like [this](https://github.com/crummel/dotnet_arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Attributes/ActiveIssueAttribute.cs) to our repo, because Failing tests shouldn't really be merged every, just skipped if the work is put of.
I'll think about how to do this, won't merge for a while

**Comment by Perksey** [comment]
+1 I think the current Silk ATG activity has proven we need this!

**Comment by WhiteBlackGoose** [comment]
Nice! The lib's almost released (I can release it any moment, just waiting if some new bug appears)

**Comment by Perksey** [comment]
Closing draft PR due to inactivity. This is useful, but there's no work happening here right now. GitHub should preserve the PR patch should we pursue this again.

**Pull request closed without merging**
