### PR TITLE
Fix/sdl2 osx-arm64

### PR DESCRIPTION
**Pull request by alexmalyutindev**
# Summary of the PR
Generating SDL2 wrapper for MacOS.

### CODE REVIEW

**Comment by Playboi2023** [comment]
Qubit its new processor 52 qubits

**Comment by Perksey** [comment]
Hey there, thanks so much for looking into contributing! Is this still in progress?

**Comment by alexmalyutindev** [comment]
Hello @Perksey , let me double check, if this is still a thing. I remember i had some problem with building it in my fork with pipeline and building it locally on my machine.

**Comment by alexmalyutindev** [comment]
@Perksey I believe you fixed it in https://github.com/dotnet/Silk.NET/commit/ef2a38667b45cc089152521773fd54accc1ab05c . Just tested pkg from nuget, works great.
PR can be closed.

**Pull request closed without merging**
